-- Canonical set abbreviations/names from user-provided set_abbr list.xlsx.
-- Keeps card_sets and card_set_aliases reproducible after the live DB import.

create temp table import_set_abbr_list (
  set_abbr text not null,
  set_name text not null,
  lang text not null
);

insert into import_set_abbr_list (set_abbr, set_name, lang) values
  ('BS', 'Base Set', 'eng'),
  ('JU', 'Jungle', 'eng'),
  ('FO', 'Fossil', 'eng'),
  ('B2', 'Base Set 2', 'eng'),
  ('TR', 'Team Rocket', 'eng'),
  ('G1', 'Gym Heroes', 'eng'),
  ('G2', 'Gym Challenge', 'eng'),
  ('N1', 'Neo Genesis', 'eng'),
  ('N2', 'Neo Discovery', 'eng'),
  ('N3', 'Neo Revelation', 'eng'),
  ('N4', 'Neo Destiny', 'eng'),
  ('LC', 'Legendary Collection', 'eng'),
  ('EX', 'Expedition Base Set', 'eng'),
  ('AQ', 'Aquapolis', 'eng'),
  ('SK', 'Skyridge', 'eng'),
  ('RS', 'EX Ruby & Sapphire', 'eng'),
  ('SS', 'EX Sandstorm', 'eng'),
  ('DR', 'EX Dragon', 'eng'),
  ('MA', 'EX Team Magma vs Team Aqua', 'eng'),
  ('HL', 'EX Hidden Legends', 'eng'),
  ('RG', 'EX FireRed & LeafGreen', 'eng'),
  ('TRR', 'EX Team Rocket Returns', 'eng'),
  ('DX', 'EX Deoxys', 'eng'),
  ('EM', 'EX Emerald', 'eng'),
  ('UF', 'EX Unseen Forces', 'eng'),
  ('DS', 'EX Delta Species', 'eng'),
  ('LM', 'EX Legend Maker', 'eng'),
  ('HP', 'EX Holon Phantoms', 'eng'),
  ('CG', 'EX Crystal Guardians', 'eng'),
  ('DF', 'EX Dragon Frontiers', 'eng'),
  ('PK', 'EX Power Keepers', 'eng'),
  ('DP', 'Diamond & Pearl', 'eng'),
  ('MT', 'Mysterious Treasures', 'eng'),
  ('SW', 'Secret Wonders', 'eng'),
  ('GE', 'Great Encounters', 'eng'),
  ('MD', 'Majestic Dawn', 'eng'),
  ('LA', 'Legends Awakened', 'eng'),
  ('SF', 'Stormfront', 'eng'),
  ('PL', 'Platinum', 'eng'),
  ('RR', 'Rising Rivals', 'eng'),
  ('SV', 'Supreme Victors', 'eng'),
  ('AR', 'Arceus', 'eng'),
  ('HS', 'HeartGold & SoulSilver', 'eng'),
  ('UL', 'Unleashed', 'eng'),
  ('UD', 'Undaunted', 'eng'),
  ('TM', 'Triumphant', 'eng'),
  ('CL', 'Call of Legends', 'eng'),
  ('BLW', 'Black & White', 'eng'),
  ('EPO', 'Emerging Powers', 'eng'),
  ('NVI', 'Noble Victories', 'eng'),
  ('NXD', 'Next Destinies', 'eng'),
  ('DEX', 'Dark Explorers', 'eng'),
  ('DRX', 'Dragons Exalted', 'eng'),
  ('DRV', 'Dragon Vault', 'eng'),
  ('BCR', 'Boundaries Crossed', 'eng'),
  ('PLS', 'Plasma Storm', 'eng'),
  ('PLF', 'Plasma Freeze', 'eng'),
  ('PLB', 'Plasma Blast', 'eng'),
  ('LTR', 'Legendary Treasures', 'eng'),
  ('KSS', 'Kalos Starter Set', 'eng'),
  ('XYB', 'XY Base', 'eng'),
  ('FLF', 'Flashfire', 'eng'),
  ('FFI', 'Furious Fists', 'eng'),
  ('PHF', 'Phantom Forces', 'eng'),
  ('PRC', 'Primal Clash', 'eng'),
  ('DCR', 'Double Crisis', 'eng'),
  ('ROS', 'Roaring Skies', 'eng'),
  ('AOR', 'Ancient Origins', 'eng'),
  ('BKT', 'BREAKthrough', 'eng'),
  ('BKP', 'BREAKpoint', 'eng'),
  ('GEN', 'Generations', 'eng'),
  ('FCO', 'Fates Collide', 'eng'),
  ('STS', 'Steam Siege', 'eng'),
  ('EVO', 'Evolutions', 'eng'),
  ('SUM', 'Sun & Moon', 'eng'),
  ('GRI', 'Guardians Rising', 'eng'),
  ('BUS', 'Burning Shadows', 'eng'),
  ('SLG', 'Shining Legends', 'eng'),
  ('CIN', 'Crimson Invasion', 'eng'),
  ('UPR', 'Ultra Prism', 'eng'),
  ('FLI', 'Forbidden Light', 'eng'),
  ('CES', 'Celestial Storm', 'eng'),
  ('DRM', 'Dragon Majesty', 'eng'),
  ('LOT', 'Lost Thunder', 'eng'),
  ('TEU', 'Team Up', 'eng'),
  ('DET', 'Detective Pikachu', 'eng'),
  ('UNB', 'Unbroken Bonds', 'eng'),
  ('UNM', 'Unified Minds', 'eng'),
  ('HIF', 'Hidden Fates', 'eng'),
  ('CEC', 'Cosmic Eclipse', 'eng'),
  ('SSH', 'Sword & Shield', 'eng'),
  ('RCL', 'Rebel Clash', 'eng'),
  ('DAA', 'Darkness Ablaze', 'eng'),
  ('CPA', 'Champion''s Path', 'eng'),
  ('VIV', 'Vivid Voltage', 'eng'),
  ('SHF', 'Shining Fates', 'eng'),
  ('BST', 'Battle Styles', 'eng'),
  ('CRE', 'Chilling Reign', 'eng'),
  ('EVS', 'Evolving Skies', 'eng'),
  ('CEL', 'Celebrations', 'eng'),
  ('CELC', 'Celebrations Classic', 'eng'),
  ('FST', 'Fusion Strike', 'eng'),
  ('BRS', 'Brilliant Stars', 'eng'),
  ('ASR', 'Astral Radiance', 'eng'),
  ('PGO', 'Pokémon GO', 'eng'),
  ('LOR', 'Lost Origin', 'eng'),
  ('SIT', 'Silver Tempest', 'eng'),
  ('CZ', 'Crown Zenith', 'eng'),
  ('SVI', 'Scarlet & Violet', 'eng'),
  ('PAL', 'Paldea Evolved', 'eng'),
  ('OBF', 'Obsidian Flames', 'eng'),
  ('MEW', '151', 'eng'),
  ('PAR', 'Paradox Rift', 'eng'),
  ('PAF', 'Paldean Fates', 'eng'),
  ('TEF', 'Temporal Forces', 'eng'),
  ('TWM', 'Twilight Masquerade', 'eng'),
  ('SFA', 'Shrouded Fable', 'eng'),
  ('SCR', 'Stellar Crown', 'eng'),
  ('SSP', 'Surging Sparks', 'eng'),
  ('PRE', 'Prismatic Evolutions', 'eng'),
  ('JTG', 'Journey Together', 'eng'),
  ('DRI', 'Destined Rivals', 'eng'),
  ('BLK', 'Black Bolt', 'eng'),
  ('WHT', 'White Flare', 'eng'),
  ('MEG', 'Mega Evolution', 'eng'),
  ('PFL', 'Phantasmal Flames', 'eng'),
  ('ASC', 'Ascended Heroes', 'eng'),
  ('POR', 'Perfect Order', 'eng'),
  ('CRI', 'Chaos Rising', 'eng'),
  ('old1', 'Base Set', 'jpn'),
  ('old2', 'Jungle', 'jpn'),
  ('old3', 'Fossil', 'jpn'),
  ('old4', 'Rocket Gang', 'jpn'),
  ('neo1', 'Neo Genesis', 'jpn'),
  ('neo2', 'Neo Discovery', 'jpn'),
  ('neo3', 'Neo Revelation', 'jpn'),
  ('neo4', 'Neo Destiny', 'jpn'),
  ('VS', 'VS Series', 'jpn'),
  ('e1', 'Expedition', 'jpn'),
  ('e2', 'Town on No Map', 'jpn'),
  ('e3', 'Wind from the Sea', 'jpn'),
  ('e4', 'Split Earth', 'jpn'),
  ('e5', 'Mysterious Mountains', 'jpn'),
  ('ADV1', 'Ruby Sapphire', 'jpn'),
  ('ADV2', 'Miracle of the Dessert', 'jpn'),
  ('ADV3', 'Rulers of the Heavens', 'jpn'),
  ('ADV4', 'Undone Seal', 'jpn'),
  ('PCG1', 'Flight of Legends', 'jpn'),
  ('PCG2', 'Clash of the Blue Sky', 'jpn'),
  ('PCG3', 'Rocket Gang Strikes Back', 'jpn'),
  ('PCG4', 'Golden Sky Silvery Ocean', 'jpn'),
  ('PCG5', 'Mirage Forest', 'jpn'),
  ('PCG6', 'Holon Research Tower', 'jpn'),
  ('PCG7', 'Holon Phantom', 'jpn'),
  ('PCG8', 'Miracle Crystal', 'jpn'),
  ('PCG9', 'Offense Defense Furthest Ends', 'jpn'),
  ('PCG10', 'World Champions Pack', 'jpn'),
  ('DP1', 'Space-Time Creation', 'jpn'),
  ('DP2', 'Secret of the Lakes', 'jpn'),
  ('DP3', 'Shining Darkness', 'jpn'),
  ('DP4', 'Moonlit Pursuit/Dawn Dash', 'jpn'),
  ('DP5', 'Cry from the Mysterious/Temple of Anger', 'jpn'),
  ('DPs', 'Stormfront', 'jpn'),
  ('Pt1', 'Galactic''s Conquest', 'jpn'),
  ('Pt2', 'Bonds to the End of Time', 'jpn'),
  ('Pt3', 'Beat of the Frontier', 'jpn'),
  ('Pt4', 'Advent of Arceus', 'jpn'),
  ('L1', 'HeartGold Collection/SoulSilver Collection', 'jpn'),
  ('L2', 'Reviving Legends', 'jpn'),
  ('L3', 'Clash at the Summit', 'jpn'),
  ('LL', 'Lost Link', 'jpn'),
  ('BW1', 'Black Collection/White Collection', 'jpn'),
  ('BW2', 'Red Collection', 'jpn'),
  ('BW3', 'Psycho Drive/Hail Blizzard', 'jpn'),
  ('BW4', 'Dark Rush', 'jpn'),
  ('BW5', 'Dragon Blast/Dragon Blade', 'jpn'),
  ('BW6', 'Freeze Bolt/Cold Flare', 'jpn'),
  ('BW7', 'Plasma Gale', 'jpn'),
  ('BW8', 'Spiral Force/Thunder Knuckle', 'jpn'),
  ('BW9', 'Megalo Cannon', 'jpn'),
  ('XY1', 'Collection X/Collection Y', 'jpn'),
  ('XY2', 'Wild Blaze', 'jpn'),
  ('XY3', 'Rising Fist', 'jpn'),
  ('XY4', 'Phantom Gale', 'jpn'),
  ('XY5', 'Gaia Volcano/Tidal Storm', 'jpn'),
  ('XY6', 'Emerald Break', 'jpn'),
  ('XY7', 'Bandit Ring', 'jpn'),
  ('XY8', 'Blue Shock/Red Flash', 'jpn'),
  ('XY9', 'Rage of Broken Heavens', 'jpn'),
  ('XY10', 'Awakening Psychic King', 'jpn'),
  ('XY11', 'Fever-Burst Fighter/Cruel Traitor', 'jpn'),
  ('SM0', 'Pikachu''s New Friends', 'jpn'),
  ('SM1S', 'Collection Sun', 'jpn'),
  ('SM1M', 'Collection Moon', 'jpn'),
  ('SM2K', 'Islands Await You', 'jpn'),
  ('SM2L', 'Alolan Moonlight', 'jpn'),
  ('SM3H', 'To Seen Battle Rainbow', 'jpn'),
  ('SM3N', 'Darkness Consumes Light', 'jpn'),
  ('SM4S', 'Awakened Heroes', 'jpn'),
  ('SM4A', 'Ultradimensional Beasts', 'jpn'),
  ('SM5S', 'Ultra Sun', 'jpn'),
  ('SM5M', 'Ultra Moon', 'jpn'),
  ('SM6', 'Forbidden Light', 'jpn'),
  ('SM7', 'Sky-Splitting Charisma', 'jpn'),
  ('SM8', 'Super-Burst Impact', 'jpn'),
  ('SM9', 'Tag Bolt', 'jpn'),
  ('SM10', 'Double Blaze', 'jpn'),
  ('SM11', 'Miracle Twin', 'jpn'),
  ('SM12', 'Alter Genesis', 'jpn'),
  ('S1W', 'Sword Collection', 'jpn'),
  ('S1H', 'Shield Collection', 'jpn'),
  ('S2', 'Rebellion Crash', 'jpn'),
  ('S3', 'Infinity Zone', 'jpn'),
  ('S4', 'Amazing Volt Tackle', 'jpn'),
  ('S5I', 'Single Strike Master', 'jpn'),
  ('S5R', 'Rapid Strike Master', 'jpn'),
  ('S6H', 'Silver Lance', 'jpn'),
  ('S6K', 'Jet-Black Spirit', 'jpn'),
  ('S7R', 'Blue Sky Stream', 'jpn'),
  ('S7D', 'Skyscraping Perfection', 'jpn'),
  ('S8', 'Fusion Arts', 'jpn'),
  ('S9', 'Star Birth', 'jpn'),
  ('S10D', 'Time Gazer', 'jpn'),
  ('S10P', 'Space Juggler', 'jpn'),
  ('S11', 'Lost Abyss', 'jpn'),
  ('S12', 'Paradigm Trigger', 'jpn'),
  ('SV1S', 'Scarlet ex', 'jpn'),
  ('SV1V', 'Violet ex', 'jpn'),
  ('SV2P', 'Snow Hazard', 'jpn'),
  ('SV2D', 'Clay Burst', 'jpn'),
  ('SV3', 'Ruler of Black Flame', 'jpn'),
  ('SV4K', 'Ancient Roar', 'jpn'),
  ('SV4M', 'Future Flash', 'jpn'),
  ('SV5K', 'Wild Force', 'jpn'),
  ('SV5M', 'Cyber Judge', 'jpn'),
  ('SV6', 'Transformation Mask', 'jpn'),
  ('SV7', 'Stellar Miracle', 'jpn'),
  ('SV8', 'Super Electric Breaker', 'jpn'),
  ('SV9', 'Battle Partners', 'jpn'),
  ('DS', 'Dragon Selection', 'jpn'),
  ('SC', 'Shiny Collection', 'jpn'),
  ('EBB', 'EX Battle Boost', 'jpn'),
  ('CP1', 'Double Crisis', 'jpn'),
  ('CP2', 'Legendary Shine Collection', 'jpn'),
  ('CP3', 'PokeKyun', 'jpn'),
  ('CP4', 'Premium Champion Pack', 'jpn'),
  ('CP5', 'Mythical Legendary Dream Shine', 'jpn'),
  ('CP6', '20th Anniversary Set', 'jpn'),
  ('BOXY', 'Best of XY', 'jpn'),
  ('SM1+', 'Sun & Moon', 'jpn'),
  ('SM2+', 'Facing a New Trial', 'jpn'),
  ('SM3+', 'Shining Legends', 'jpn'),
  ('SM4+', 'GX Battle Boost', 'jpn'),
  ('SM5+', 'Ultra Force', 'jpn'),
  ('SM6a', 'Dragon Storm', 'jpn'),
  ('SM6b', 'Champion Road', 'jpn'),
  ('SM7a', 'Thunderclap Spark', 'jpn'),
  ('SM7b', 'Fairy Rise', 'jpn'),
  ('SM8a', 'Dark Order', 'jpn'),
  ('SM8b', 'Ultra Shiny GX', 'jpn'),
  ('SM9a', 'Night Unison', 'jpn'),
  ('SM9b', 'Full Metal Wall', 'jpn'),
  ('SM10a', 'GG End', 'jpn'),
  ('SM10b', 'Sky Legend', 'jpn'),
  ('SM11a', 'Remix Bout', 'jpn'),
  ('SM11b', 'Dream League', 'jpn'),
  ('SM12a', 'Tag Team All Stars', 'jpn'),
  ('S1a', 'VMAX Rising', 'jpn'),
  ('S2a', 'Explosive Walker', 'jpn'),
  ('S3a', 'Legendary Heartbeat', 'jpn'),
  ('S4a', 'Shiny Star V', 'jpn'),
  ('S5a', 'Peerless Fighters', 'jpn'),
  ('S6a', 'Eevee Heroes', 'jpn'),
  ('S8a', '25th Anniversary Set', 'jpn'),
  ('S8b', 'VMAX Climax', 'jpn'),
  ('S9a', 'Battle Region', 'jpn'),
  ('S10a', 'Dark Phantasma', 'jpn'),
  ('S10b', 'Pokemon GO', 'jpn'),
  ('S11a', 'Incandescent Arcana', 'jpn'),
  ('S12a', 'VSTAR Universe', 'jpn'),
  ('SV1a', 'Triplet Beat', 'jpn'),
  ('SV2a', '151', 'jpn'),
  ('SV3a', 'Raging Surf', 'jpn'),
  ('SV4a', 'Shiny Treasure', 'jpn'),
  ('SV5a', 'Crimson Haze', 'jpn'),
  ('SV6a', 'Night Wanderer', 'jpn'),
  ('SV7a', 'Paradise Dragona', 'jpn'),
  ('SV8a', 'Terastal Festival', 'jpn'),
  ('SV9a', 'Heat Wave Arena', 'jpn'),
  ('SV10', 'Glory of Team Rocket', 'jpn'),
  ('SV11B', 'Black Bolt', 'jpn'),
  ('SV11W', 'White Flare', 'jpn'),
  ('M1S', 'Mega Symphonia', 'jpn'),
  ('M1L', 'Mega Brave', 'jpn'),
  ('M2', 'Inferno X', 'jpn'),
  ('M2a', 'Mega Dream', 'jpn'),
  ('M3', 'Nihil Zero', 'jpn'),
  ('M4', 'Ninja Spinner', 'jpn'),
  ('M5', 'Pitch Black', 'jpn');

update card_sets cs
set canonical_set_name = i.set_name,
    source = 'set_abbr_list_xlsx',
    updated_at = now()
from import_set_abbr_list i
where lower(cs.set_abbr) = lower(i.set_abbr)
  and cs.lang = i.lang
  and (cs.canonical_set_name is distinct from i.set_name or cs.source is distinct from 'set_abbr_list_xlsx');

insert into card_sets (set_abbr, lang, canonical_set_name, source, notes)
select i.set_abbr, i.lang, i.set_name, 'set_abbr_list_xlsx', 'Imported from user-provided set_abbr list.xlsx'
from import_set_abbr_list i
where not exists (
  select 1 from card_sets cs
  where lower(cs.set_abbr) = lower(i.set_abbr)
    and cs.lang = i.lang
);

insert into card_set_aliases (card_set_id, alias_name, alias_set_code, alias_language_text, source, confidence, notes)
select cs.id,
       i.set_name,
       i.set_abbr,
       case when i.lang = 'jpn' then 'JAPANESE' when i.lang = 'eng' then 'ENGLISH' else upper(i.lang) end,
       'set_abbr_list_xlsx',
       'manual',
       'Imported from user-provided set_abbr list.xlsx'
from import_set_abbr_list i
join card_sets cs on lower(cs.set_abbr) = lower(i.set_abbr) and cs.lang = i.lang
on conflict do nothing;

insert into card_set_aliases (card_set_id, alias_name, alias_set_code, alias_language_text, source, confidence, notes)
select cs.id,
       i.set_name,
       null,
       case when i.lang = 'jpn' then 'JAPANESE' when i.lang = 'eng' then 'ENGLISH' else upper(i.lang) end,
       'set_abbr_list_xlsx',
       'manual',
       'Imported from user-provided set_abbr list.xlsx; language-qualified alias.'
from import_set_abbr_list i
join card_sets cs on lower(cs.set_abbr) = lower(i.set_abbr) and cs.lang = i.lang
on conflict do nothing;
